version: 2.1
commands:
  bundle_install_and_test:
    steps:
      - checkout
      - run: sudo gem update --system
      - run: bundle install
      - run: bundle exec rubocop
      - run: bundle exec appraisal install
      - run: bundle exec appraisal rake test

jobs:
  test-ruby-263:
    steps:
      - bundle_install_and_test
    docker:
      - image: circleci/ruby:2.6.3
  test-ruby-271:
    steps:
      - bundle_install_and_test
    docker:
      - image: circleci/ruby:2.7.1

workflows:
  rc:
    jobs:
      - test-ruby-263
      - test-ruby-271
